version: '3.8'
services:
  web:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    container_name: artemis-flask-app # Optional: custom container name
    restart: unless-stopped # Optional: restart policy
